name: 'UNCLE: UNited Computer security Lab-E'
favicon: null
layout_spectrum: 0.09985
typography_spectrum: 0.90724
title: 'UNCLE: UNited Computer security Lab-E'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1210'
    - '#711615'
    - '#746550'
    - '#9b9a95'
    - '#cfd0cb'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.2139099061023444
  rhythmicContrast: 0.7103247665800154
purpose: []
