name: UNCLE
favicon: null
layout_spectrum: 0.05630813958123326
typography_spectrum: 0.37024818966165185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.42930917581543326
  lightness: 0.4895835961215198
  saturation: 0.2139099061023444
  rhythmicContrast: 0.7103247665800154
purpose: []
